// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const Role = {
  "CONCERTMANAGER": "CONCERTMANAGER",
  "STAGEMANAGER": "STAGEMANAGER",
  "MUSICDIRECTOR": "MUSICDIRECTOR",
  "TOURMANAGER": "TOURMANAGER",
  "PRODUCTIONMANAGER": "PRODUCTIONMANAGER",
  "COMPANYMANAGER": "COMPANYMANAGER",
  "LIBRARIAN": "LIBRARIAN",
  "CONCERTMASTER": "CONCERTMASTER",
  "PRINCIPAL": "PRINCIPAL",
  "VICEPRINCIPAL": "VICEPRINCIPAL",
  "SECTION": "SECTION",
  "GUESTARTIST": "GUESTARTIST",
  "VIDEOGRAPHER": "VIDEOGRAPHER",
  "SOUNDENGINEER": "SOUNDENGINEER",
  "USHER": "USHER",
  "STAGECREW": "STAGECREW",
  "LIGHTING": "LIGHTING",
  "CEO": "CEO",
  "COO": "COO",
  "CTO": "CTO",
  "DEVELOPMENT": "DEVELOPMENT"
};

const Sections = {
  "SOPRANO": "SOPRANO",
  "ALTO": "ALTO",
  "TENOR": "TENOR",
  "BASS": "BASS",
  "CONDUCTOR": "CONDUCTOR",
  "COMPOSER": "COMPOSER",
  "PICCOLO": "PICCOLO",
  "FLUTE": "FLUTE",
  "CLARINET": "CLARINET",
  "OBOE": "OBOE",
  "BASSOON": "BASSOON",
  "HORN": "HORN",
  "SOPRANOSAXOPHONE": "SOPRANOSAXOPHONE",
  "TRUMPET": "TRUMPET",
  "TROMBONE": "TROMBONE",
  "BASSTROMBONE": "BASSTROMBONE",
  "TUBA": "TUBA",
  "VIOLINI": "VIOLINI",
  "VIOLA": "VIOLA",
  "CELLO": "CELLO",
  "CONTRABASS": "CONTRABASS",
  "PERCUSSION": "PERCUSSION",
  "VIOLINII": "VIOLINII",
  "PIANO": "PIANO",
  "HARP": "HARP",
  "ENGLISHHORN": "ENGLISHHORN",
  "BASSCLARINET": "BASSCLARINET",
  "EBCLARINET": "EBCLARINET",
  "ALTOSAXOPHONE": "ALTOSAXOPHONE",
  "TENORSAXOPHONE": "TENORSAXOPHONE",
  "BARITONESAXOPHONE": "BARITONESAXOPHONE",
  "SAXOPHONE": "SAXOPHONE",
  "NONMUSICIAN": "NONMUSICIAN",
  "EUPHONIUM": "EUPHONIUM"
};

const { ORGANIZATION, EMPLOYEEE } = initSchema(schema);

export {
  ORGANIZATION,
  EMPLOYEEE,
  Role,
  Sections
};